import {Chess} from './chess.js';
import {engine,applyUci,uciMove,scoreNumber} from './engine.js';
import {extendContinuation} from './lookahead.js';
const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'},icons={p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'};
export function describePosition(fen,move){const g=new Chess(fen);if(g.isCheckmate())return 'Checkmate: the king is attacked and has no legal escape.';if(g.isDraw())return 'This continuation reaches a draw under the position’s rules.';if(!move)return 'Compare the branches. Each is one line of engine analysis, not a forced prediction of the whole game.';const mover=g.turn()==='w'?'Black':'White';let text=`${mover} moved a ${names[move.piece]} from ${move.from} to ${move.to}${move.captured?', capturing a '+names[move.captured]:''}. `;if(g.isCheck())text+='The king is in check, so the next move must answer that attack. ';const exposed=g.board().flat().filter(p=>p&&p.color===g.turn()&&p.type!=='k'&&g.isAttacked(p.square,p.color==='w'?'b':'w')&&!g.isAttacked(p.square,p.color));if(exposed.length)text+='Watch the undefended '+exposed.map(p=>names[p.type]+' on '+p.square).join(', ')+'.';return text;}
function evalLabel(line){if(line.mate!=null)return `${line.mate>0?'White':'Black'}: engine finds mate in ${Math.abs(line.mate)}`;let value=(line.cp||0)/100;return Math.abs(value)<.3?'Approximately balanced':`${value>0?'White':'Black'} favored · ${Math.abs(value).toFixed(1)} pawns`;}
export function mountAnalysis(document,getPosition){const $=id=>document.getElementById(id);let openedFen,openedPending=null,rootFen,analysisFen,initialMove=null,result=null,lineIndex=0,step=0,ticket=0,currentFen=null,extensionTicket=0,extending=false;
 function paint(){$('analysis-extend').disabled=extending||!result?.lines?.length;$('analysis-stop').hidden=!extending;let line=result?.lines[lineIndex],moves=line?.moves||[],position=step?moves[step-1]?.after:analysisFen;currentFen=position;const g=new Chess(position);$('analysis-board').innerHTML='';for(let r=8;r>=1;r--)for(let f=0;f<8;f++){let sq=String.fromCharCode(97+f)+r,p=g.get(sq),tile=document.createElement('div');tile.className='square'+((f+r)%2===0?' dark':'');tile.innerHTML=(p?`<span class="piece ${p.color==='w'?'white':'black'}">${icons[p.type]}</span>`:'')+`<span class="map-coordinate">${sq}</span>`;tile.setAttribute('aria-label',`${sq}: ${p?(p.color==='w'?'white ':'black ')+names[p.type]:'empty'}`);if(step&&(moves[step-1].from===sq||moves[step-1].to===sq))tile.className+=' last';$('analysis-board').append(tile);}
 $('analysis-continue').disabled=!result||g.isGameOver();$('line-prev').disabled=step===0;$('line-next').disabled=step>=moves.length;$('analysis-step').textContent=step===0?(initialMove?`After your candidate ${initialMove.san}`:'Starting position'):`${step} / ${moves.length} half-moves`;$('analysis-explanation').textContent=describePosition(position,step?moves[step-1]:initialMove);$('analysis-evaluation').textContent=line?evalLabel(line):result?'No continuation: this position is finished.':'Calculating…';$('analysis-depth').textContent=line?`Stockfish 17.1 Lite · depth ${line.depth} · initial-position evaluation from White’s perspective`:'';
 $('branch-tabs').innerHTML=(result?.lines||[]).map((l,i)=>`<button data-line="${i}" class="${i===lineIndex?'active':''}">${l.moves[0]?.san||'End'}<small>${evalLabel(l)}</small></button>`).join('');$('branch-tabs').querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>{lineIndex=+b.dataset.line;step=0;extensionTicket++;extending=false;$('analysis-status').textContent='Selected this reply. Step through it or build its 20-move continuation.';paint();});$('line-moves').innerHTML=moves.map((m,i)=>`<button data-step="${i+1}" class="${step===i+1?'active':''}">${i+1}. ${m.san}</button>`).join('');$('line-moves').querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;paint();});}
 async function analyze(){extensionTicket++;extending=false;const id=++ticket;result=null;lineIndex=0;step=0;const g=new Chess(rootFen),choice=$('candidate-move').value;initialMove=choice?applyUci(g,choice):null;analysisFen=g.fen();$('analysis-status').textContent='Calculating useful continuations…';$('analysis-refresh').disabled=true;$('branch-tabs').innerHTML='';paint();try{const data=await engine.analyze(analysisFen,{time:1600,multipv:3,depth:18});if(id!==ticket)return;result=data;paint();$('analysis-status').textContent=initialMove?'Strong replies to your candidate. Select a reply, then step through the continuation.':'Compare the strongest candidates found within this analysis time.';}catch(e){if(id===ticket)$('analysis-status').textContent=e.message+' Your game and legal-move map still work.';}finally{if(id===ticket)$('analysis-refresh').disabled=false;}}
 function candidates(candidate=null){const g=new Chess(rootFen),moves=g.moves({verbose:true});$('candidate-move').innerHTML='<option value="">Compare top candidates</option>'+moves.map(m=>`<option value="${uciMove(m)}">${m.san} · ${m.from} → ${m.to}${m.promotion?' = '+names[m.promotion]:''}</option>`).join('');$('candidate-move').value=candidate?uciMove(candidate):'';$('analysis-legal-count').textContent=`All ${moves.length} legal moves in this position are available in the menu.`;}
 $('open-analysis').onclick=()=>{const state=getPosition();openedFen=state.fen;openedPending=state.pending;rootFen=openedFen;$('analysis-origin').value='current';candidates(openedPending);$('analysis-dialog').showModal();analyze();};
 $('analysis-origin').onchange=()=>{rootFen=$('analysis-origin').value==='start'?new Chess().fen():openedFen;candidates($('analysis-origin').value==='current'?openedPending:null);analyze();};
 $('analysis-continue').onclick=()=>{if(!currentFen)return;rootFen=currentFen;$('analysis-origin').value='branch';candidates();analyze();};
 $('analysis-extend').onclick=async()=>{const line=result?.lines[lineIndex];if(!line||extending)return;const id=++extensionTicket;extending=true;paint();try{const extended=await extendContinuation(analysisFen,line.moves,engine.analyze.bind(engine),{turns:40,cancelled:()=>id!==extensionTicket,onProgress:n=>{$('analysis-status').textContent=`Building this continuation: ${n} / 40 alternating turns…`;}});if(!extended||id!==extensionTicket)return;line.moves=extended.moves;line.pv=extended.moves.map(m=>m.uci);$('analysis-status').textContent=extended.terminal?`This line ends after ${extended.moves.length} turns: checkmate or draw.`:'20-move continuation ready: 40 alternating turns. Later sections use fresh searches, not one exhaustive 20-move calculation.';}catch(e){if(id===extensionTicket)$('analysis-status').textContent=e.message;}finally{if(id===extensionTicket){extending=false;paint();}}};
 $('analysis-stop').onclick=()=>{extensionTicket++;extending=false;$('analysis-status').textContent='Stopped extending. You can still explore the original line.';paint();};
 $('candidate-move').onchange=analyze;$('analysis-refresh').onclick=analyze;$('analysis-close').onclick=()=>{ticket++;extensionTicket++;extending=false;$('analysis-dialog').close();};$('analysis-dialog').addEventListener('close',()=>{ticket++;extensionTicket++;extending=false;});$('line-prev').onclick=()=>{step=Math.max(0,step-1);paint();};$('line-next').onclick=()=>{step=Math.min(result?.lines[lineIndex]?.moves.length||0,step+1);paint();};$('analysis-dialog').addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();if(e.key==='ArrowRight')$('line-next').onclick();else $('line-prev').onclick();}});
}
export function createNotebook(storage){let cards=[];try{const raw=JSON.parse(storage.getItem('bloom-mistakes-v1')||'[]');if(Array.isArray(raw))cards=raw.filter(c=>{try{return typeof c.id==='string'&&typeof c.best==='string'&&!!new Chess(c.fen)&&!!applyUci(new Chess(c.fen),c.best)&&!!applyUci(new Chess(c.fen),c.played)&&Number.isFinite(c.loss);}catch{return false;}}).slice(0,30);}catch{}
 const save=()=>{try{storage.setItem('bloom-mistakes-v1',JSON.stringify(cards));}catch{}};
 return {all:()=>cards,add(card){if(cards.some(c=>c.fen===card.fen&&c.played===card.played))return;cards.unshift({...card,id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),solved:false,attempts:0});cards=cards.slice(0,30);save();},complete(id){const c=cards.find(c=>c.id===id);if(c){c.solved=true;c.attempts++;save();}},attempt(id){const c=cards.find(c=>c.id===id);if(c){c.attempts++;save();}}};
}
export async function findLearningMoment(fen,played){const g=new Chess(fen),actual=applyUci(g,played);const before=await engine.analyze(fen,{time:800,multipv:1,depth:16});if(!before.lines[0])return null;const best=before.lines[0];if(best.pv[0]===played)return null;let after;if(g.isCheckmate())return null;if(g.isDraw())after={cp:0};else after=(await engine.analyze(g.fen(),{time:800,multipv:1,depth:16})).lines[0];if(!after)return null;const loss=(scoreNumber(best)-scoreNumber(after))*(new Chess(fen).turn()==='w'?1:-1);if(loss<120)return null;return {fen,played,best:best.pv[0],loss:Math.min(loss,10000),explanation:`Your ${names[actual.piece]} moved ${actual.from} → ${actual.to}. A short engine review found a stronger alternative. Find a move that keeps more of the position’s value.`,depth:Math.min(best.depth,after.depth||best.depth)};}
