export const lessons = [
  {chapter:'Meet your pieces',name:'Make room to grow',piece:'♟',text:'Pawns move forward, but capture diagonally. On its first move, a pawn can move two squares. Move e2 to e4.',from:'e2',to:'e4',why:'Your pawn now attacks d5 and f5. Moving it also opens paths for your bishop and queen.'},
  {chapter:'Meet your pieces',name:'The jumping knight',piece:'♞',text:'A knight moves two squares one way, then one sideways. It can jump over pieces. Move g1 to f3.',from:'g1',to:'f3',why:'On f3 your knight controls central squares d4 and e5. Knights usually have more choices near the center.'},
  {chapter:'Meet your pieces',name:'Open a diagonal',piece:'♝',text:'Bishops travel diagonally and cannot jump. Move your bishop from f1 to c4.',fen:'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',from:'f1',to:'c4',why:'Your bishop now looks down the diagonal toward f7. Developing means bringing pieces into useful positions.'},
  {chapter:'Meet your pieces',name:'Use your rook',piece:'♜',text:'Rooks travel along rows and columns. Move a1 to a7 to capture the pawn.',fen:'7k/p7/8/8/8/8/7P/R5K1 w - - 0 1',from:'a1',to:'a7',why:'An open file is a column with no pawns blocking it. Your rook used one to reach the pawn.'},
  {chapter:'Meet your pieces',name:'Meet the queen',piece:'♛',text:'A queen combines a rook’s straight moves and a bishop’s diagonals. Capture the pawn on h5 with your queen on d1.',fen:'k7/8/8/7p/8/8/P7/3Q2K1 w - - 0 1',from:'d1',to:'h5',why:'The queen traveled diagonally through e2, f3 and g4. She is powerful, so check her destination for danger.'},
  {chapter:'Keep your king safe',name:'Escape from check',piece:'♚',text:'Check means your king is attacked. Move your king from e1 to f1, away from the rook’s file.',fen:'k3r3/8/8/8/8/8/P7/4K3 w - - 0 1',from:'e1',to:'f1',why:'A king may never stay in check. Moving off the e-file removed the rook’s attack.'},
  {chapter:'Keep your king safe',name:'Block an attack',piece:'♝',text:'Sometimes you can block a check. Move your bishop from d2 to e3 to interrupt the rook’s attack.',fen:'k3r3/8/8/8/8/8/3B4/4K3 w - - 0 1',from:'d2',to:'e3',why:'Your bishop stands between the rook and king. You cannot block a knight’s check: its attack jumps.'},
  {chapter:'Keep your king safe',name:'Capture the attacker',piece:'♚',text:'A king can capture an unprotected attacker. Move e1 to e2 to take the checking rook.',fen:'k7/8/8/8/8/8/4r3/4K3 w - - 0 1',from:'e1',to:'e2',why:'The rook had no defender, so your king could safely capture it. Only two kings remain: the position is a draw.'},
  {chapter:'Keep your king safe',name:'Castle to safety',piece:'♚',text:'Castling moves your king and rook together. Neither can have moved; the king’s path must be clear and safe. Move e1 to g1.',fen:'rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',from:'e1',to:'g1',why:'Your king moved to g1 and rook to f1. You cannot castle out of check, through check, or into check.'},
  {chapter:'Discover tactical ideas',name:'Attack two pieces',piece:'♞',text:'A fork attacks two pieces at once. Move your knight from d5 to f6 to attack the king and queen.',fen:'4k3/8/8/3N3q/8/8/8/6K1 w - - 0 1',from:'d5',to:'f6',why:'Your knight checks the king on e8 and attacks the queen on h5. Black must answer the check first.'},
  {chapter:'Discover tactical ideas',name:'Promote a pawn',piece:'♛',text:'Reach the far edge to turn a pawn into a queen, rook, bishop, or knight. Move a7 to a8 and choose your new piece.',fen:'7k/P7/8/8/8/8/8/6K1 w - - 0 1',from:'a7',to:'a8',why:'Promotion can change the game. A queen is usually strongest, but another piece can sometimes avoid stalemate or deliver a useful check.'},
  {chapter:'Discover tactical ideas',name:'The special pawn capture',piece:'♟',text:'Black has just moved d7 to d5. Your pawn on e5 can capture it as if it stopped on d6. Move e5 to d6.',fen:'7k/8/8/3pP3/8/8/8/6K1 w - d6 0 1',from:'e5',to:'d6',why:'This is en passant. It is only available immediately after the opposing pawn advances two squares beside yours.'}
];
export const puzzles = [
 {name:'The last rank',theme:'Checkmate',fen:'6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',text:'Find checkmate in one move.',from:'e1',to:'e8',mate:true,hints:['The black king has very little room behind its pawns.','Use your rook to attack along the back rank.','Move the rook from e1 to e8.'],why:'The rook attacks the entire back rank. The pawns stop the king moving forward, and Black cannot block or capture the rook.'},
 {name:'Queen and king, together',theme:'Checkmate',fen:'7k/8/5KQ1/8/8/8/8/8 w - - 0 1',text:'Find checkmate in one move.',from:'g6',to:'g7',mate:true,hints:['Your king can protect the queen near the enemy king.','Put the queen beside the black king, on a square your king protects.','Move the queen from g6 to g7.'],why:'Your king protects the queen on g7. The queen attacks h8 and covers all the king’s escape squares.'},
 {name:'A royal fork',theme:'Fork · 2 moves',fen:'4k3/8/8/3N3q/8/8/8/6K1 w - - 0 1',text:'Force the king to move, then win the queen.',from:'d5',to:'f6',reply:'Kf8',follow:{from:'f6',to:'h5'},hints:['Look for a check that also attacks a valuable piece.','A knight can attack the king and queen at once.','Play d5 to f6. After the king moves, capture h5.'],why:'The check forced Black to move its king. That gave your knight time to capture the queen.'},
 {name:'Take what is free',theme:'Undefended piece',fen:'k7/8/8/8/7q/8/P7/6KR w - - 0 1',text:'Capture Black’s unprotected queen.',from:'h1',to:'h4',hints:['Look for a valuable piece with no defender.','Your rook and the black queen share a file.','Move your rook from h1 to h4.'],why:'The queen was unprotected on an open file. A quick scan for undefended pieces can reveal simple wins.'},
 {name:'Rescue your king',theme:'Answer a check',fen:'k3r3/8/8/8/8/8/3B4/4K3 w - - 0 1',text:'Block the check with your bishop.',from:'d2',to:'e3',hints:['Trace the line from the black rook to your king.','Your bishop can stand in the rook’s way.','Move the bishop from d2 to e3.'],why:'Placing the bishop on e3 interrupts the attack. When checked, consider moving, blocking, or capturing.'},
 {name:'Win a rook',theme:'Knight fork · 2 moves',fen:'4k3/8/8/3N3r/8/8/P7/6K1 w - - 0 1',text:'Check with your knight, then capture the rook.',from:'d5',to:'f6',reply:'Kf8',follow:{from:'f6',to:'h5'},hints:['A forcing move makes the opponent respond to your plan.','From f6, a knight attacks e8 and h5.','Move d5 to f6; after Black replies, capture h5.'],why:'Checking first prevented Black from saving the rook. This is why checks are worth examining before other moves.'},
 {name:'Diagonal opportunity',theme:'Bishop capture',fen:'k7/8/8/8/7r/8/8/4B1K1 w - - 0 1',text:'Find a safe way to capture Black’s rook.',from:'e1',to:'h4',hints:['Follow the bishop’s diagonals.','The rook is on the e1–h4 diagonal.','Move your bishop from e1 to h4.'],why:'Your bishop took an undefended rook. Bishops can reach distant targets along clear diagonals.'},
 {name:'A new queen',theme:'Promotion',fen:'7k/P7/8/8/8/8/8/6K1 w - - 0 1',text:'Promote your pawn to a queen.',from:'a7',to:'a8',promotion:'q',hints:['Your pawn is one step from the far edge.','Reach the eighth rank and choose a queen.','Move a7 to a8 and select Queen.'],why:'Your pawn became a queen and gave check. In a real game, keep checking for stalemate as you try to finish.'}
];
