import {Chess} from './chess.js';
export const uciMove=m=>m.from+m.to+(m.promotion||'');
export function applyUci(game,text){if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(text))throw new Error('Invalid engine move');return game.move({from:text.slice(0,2),to:text.slice(2,4),promotion:text[4]||'q'});}
export function parseInfo(line,turn){
 const depth=line.match(/\bdepth (\d+)/),score=line.match(/\bscore (cp|mate) (-?\d+)/),pv=line.match(/\bpv (.+)$/);if(!depth||!score||!pv||/\b(upperbound|lowerbound)\b/.test(line))return null;
 const side=turn==='w'?1:-1,value=Number(score[2]);return {depth:+depth[1],rank:+(line.match(/\bmultipv (\d+)/)?.[1]||1),cp:score[1]==='cp'?side*value:null,mate:score[1]==='mate'?side*value:null,pv:pv[1].trim().split(/\s+/)};
}
export function scoreNumber(line){return line?.mate!=null?Math.sign(line.mate||1)*(100000-Math.abs(line.mate)*100):line?.cp??0;}
export function legalLine(fen,pv){const g=new Chess(fen),moves=[];for(const raw of pv){try{const m=applyUci(g,raw);moves.push({from:m.from,to:m.to,piece:m.piece,captured:m.captured,san:m.san,after:g.fen(),uci:raw});if(g.isGameOver())break;}catch{break;}}return moves;}
export class ChessEngine {
 constructor(factory=()=>new Worker(new URL('./engine/stockfish-17.1-lite-single-03e3232.js',import.meta.url))){this.factory=factory;this.queue=Promise.resolve();this.ready=null;this.worker=null;this.listener=null;this.status='not loaded';}
 boot(){if(this.ready)return this.ready;this.status='loading';this.ready=new Promise((resolve,reject)=>{let timeout=setTimeout(()=>fail(new Error('The analysis engine took too long to load.')),25000);const fail=error=>{clearTimeout(timeout);this.status='unavailable';this.ready=null;this.worker?.terminate();reject(error);};try{this.worker=this.factory();this.worker.onerror=()=>{const error=new Error('Analysis could not start in this browser.');fail(error);this.activeReject?.(error);};this.worker.onmessage=event=>{for(const line of String(event.data).split('\n')){if(line==='uciok'){this.send('setoption name Hash value 32');this.send('isready');}else if(line==='readyok'&&this.status==='loading'){clearTimeout(timeout);this.status='ready';resolve();}this.listener?.(line);}};this.send('uci');}catch(e){fail(e);}});return this.ready;}
 send(command){this.worker.postMessage(command);}
 analyze(fen,{time=900,multipv=3,depth=16,skill=20}={}){const task=async()=>{await this.boot();const g=new Chess(fen);if(g.isGameOver())return {fen,lines:[],best:null,terminal:true};return new Promise((resolve,reject)=>{const lines=new Map();let timeout;const finish=(error,result)=>{clearTimeout(timeout);this.listener=null;this.activeReject=null;error?reject(error):resolve(result);};this.activeReject=error=>finish(error);timeout=setTimeout(()=>{this.send('stop');finish(new Error('Analysis timed out. Please try again.'));this.worker.terminate();this.ready=null;this.status='unavailable';},time+10000);this.listener=line=>{const info=parseInfo(line,g.turn());if(info){const valid=legalLine(fen,info.pv);if(valid.length)lines.set(info.rank,{...info,moves:valid,pv:valid.map(m=>m.uci)});}if(line.startsWith('bestmove ')){const best=line.split(' ')[1];const result=[...lines.values()].sort((a,b)=>a.rank-b.rank);if(!result.length){finish(new Error('No reliable line was returned.'));return;}finish(null,{fen,lines:result,best,terminal:false});}};this.send('setoption name MultiPV value '+Math.min(3,Math.max(1,multipv)));this.send('setoption name Skill Level value '+Math.min(20,Math.max(0,skill)));this.send('position fen '+fen);this.send(`go depth ${depth} movetime ${time}`);});};const promise=this.queue.then(task,task);this.queue=promise.catch(()=>{});return promise;}
}
export const engine=new ChessEngine();
